-- Resolving an invitation from its token, before anyone is signed in.
--
-- An invitation could not be redeemed by anyone who did not already have an
-- account, and nothing created one: the sign-in form sends a magic link with
-- shouldCreateUser: false, so an invited address that had never signed in got
-- `422 otp_disabled` and — because the form reports that as success, to avoid
-- confirming whether an address is registered — a page saying the link was on
-- its way. No invitation had ever been accepted.
--
-- The token is what fixes it. It is 64 hex characters, generated by a column
-- default, and only ever sent to the invited address, so holding one *is* the
-- authorisation to make an account for that address. Taking the token rather
-- than an email is the point: a `has_pending_invite(email)` helper would tell
-- anyone with the publishable key whether a given address had been invited,
-- and this cannot be asked that question.
--
-- Returns null for a token that is unknown, expired, or already used — the
-- three are deliberately indistinguishable.

create function public.invite_email_for_token(p_token text) returns jsonb
language sql stable security definer set search_path = public, extensions, pg_temp as $$
  select jsonb_build_object(
    'email',          i.email::text,
    'role',           case when i.workspace_id is null then null else i.role end,
    'workspace_name', w.name,
    'app',            w.app,
    'granted_apps',   to_jsonb(i.grant_apps)
  )
  from public.workspace_invites i
  left join public.workspaces w on w.id = i.workspace_id
  where i.token = p_token
    and i.accepted_at is null
    and i.expires_at > now()
$$;

-- anon needs this: the whole point is the caller has no session yet.
revoke all on function public.invite_email_for_token(text) from public;
grant execute on function public.invite_email_for_token(text) to anon, authenticated;
